server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgmis
    #    url: jdbc:mysql://42.193.192.61:3306/sgmis
    username: root
    password: 799823
  #    password: guatdev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0

encrypt:
  memoryPowOfTwo: 13
  iterations: 9
  parallelism: 5
  hashLength: 512

jwt:
  #秒
  expires: 21600
  update-gap: 1800
  secret-key: S&h(i(to*A@E#
  ipLimit: 3

# 配置信息的表名，防止sql注入
xxpz:
  tableNames: yspz, lxpz, yanpz, jbpz, ylhl, gdcgzt, breeder, country, province, state
  systemGid: 0

user:
  defaultPassword: 123456

file:
  logo:
    path: logo
    type: image/jpeg, image/png, image/gif, image/tiff
  pigeon:
    path: pigeon
    type: image/jpeg, image/png, image/gif, image/tiff

pigeon:
  generation:
    limit: 7

page:
  maxLimit: 10000

carousel:
  limit: 10

# 天
recent:
  create: 30
  delete: 30
  oplog: 30

#day
log:
  maxHistory: 180

QR:
  width: 168
  height: 168
  image-format: png
  charset: utf-8
  base64-image: data:image/png;base64,%s
  logo-url: system/logo/logo.jpg
  background: 0xFFFFFF
  foreground: 0x000000
  logo-width: 36
  logo-height: 36

feedback:
  githubUrl: https://github.com/Shi-AE/sgmis
  guatUrl: https://www.guat.edu.cn
  mailUrl: mailto:2021070030101@guat.edu.cn

template:
  pigeon: template/pigeonTemplate.xlsx