server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sgmis
    username: root
    password: 799823
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10MB

encrypt:
  memoryPowOfTwo: 13
  iterations: 9
  parallelism: 5
  hashLength: 512

jwt:
  #秒
  expires: 21600
  secret-key: S&h(i(to*A@E#
  #分钟
  update-gap: 30

# 配置信息的表名，防止sql注入
xxpz:
  tableNames: yspz, lxpz, yanpz, jbpz, ylhl, gdcgzt
  systemGid: 0

user:
  defaultPassword: 123456

file:
  logo:
    path: logo
    type: image/jpeg, image/png, image/gif, image/tiff
  pigeon:
    path: pigeon
    type: image/jpeg, image/png, image/gif, image/tiff

pigeon:
  generation:
    limit: 7

page:
  maxLimit: 10000

carousel:
  limit: 10

# 月
recent:
  create: 1
  delete: 1
  oplog: 1